<?php
/**
 * @file
 * cms_blog_content.features.uuid_file_entity.inc
 */

/**
 * Implements hook_uuid_features_default_file_entities().
 */
function cms_blog_content_uuid_features_default_file_entities() {
  $files = array();

  $files[] = array(
    'filename' => '11hochbunker.jpg.jpg',
    'uri' => 'public://11hochbunker.jpg.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 330210,
    'status' => 1,
    'type' => 'image',
    'uuid' => '06a2cb45-1224-4567-bb58-a29b68912338',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/11hochbunker.jpg.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1436367050586-7c605120bf73.jpg',
    'uri' => 'public://blog-images/photo-1436367050586-7c605120bf73.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 190455,
    'status' => 1,
    'type' => 'image',
    'uuid' => '29a20c3d-4a71-42a5-aebf-2f7b657fd331',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1328,
      'width' => 1920,
    ),
    'height' => 1328,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1436367050586-7c605120bf73.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1453133451515-5ff7c1d0d63c.jpg',
    'uri' => 'public://photo-1453133451515-5ff7c1d0d63c.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 277153,
    'status' => 1,
    'type' => 'image',
    'uuid' => '63198bff-44bf-46f2-b600-5dd2c95d5d7e',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1080,
      'width' => 1920,
    ),
    'height' => 1080,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1453133451515-5ff7c1d0d63c.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1486108334972-f02b6c78ba07.jpg',
    'uri' => 'public://photo-1486108334972-f02b6c78ba07.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 749806,
    'status' => 1,
    'type' => 'image',
    'uuid' => '63f25ea3-fc89-4806-ab3b-8a8a9880f040',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1486108334972-f02b6c78ba07.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1462887414461-cceed5385e2c.jpg',
    'uri' => 'public://photo-1462887414461-cceed5385e2c_1.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 325198,
    'status' => 1,
    'type' => 'image',
    'uuid' => '85d716a5-4ddf-4881-b4ea-489befc2d013',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1462887414461-cceed5385e2c_1.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1466298356323-f84bed7b3475.jpg',
    'uri' => 'public://photo-1466298356323-f84bed7b3475.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 262804,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'b69d1559-9d07-4288-8912-e12e3e048485',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1466298356323-f84bed7b3475.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1495991700551-167458546ddb.jpg',
    'uri' => 'public://photo-1495991700551-167458546ddb.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 262577,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'ebd89af3-12f3-4316-8c97-84e0182ad497',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1495991700551-167458546ddb.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  $files[] = array(
    'filename' => 'photo-1476733636740-24c58e0e7432.jpg',
    'uri' => 'public://photo-1476733636740-24c58e0e7432.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 377931,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'ffc16977-1c5c-43fb-aeb0-304385a94a5c',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/photo-1476733636740-24c58e0e7432.jpg',
    'user_uuid' => 'f3a5fbb6-f1ba-4c51-956c-a81a485017f7',
  );
  return $files;
}
