<?php

namespace OPCache;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-03-12 at 16:18:04.
 */
class OPCacheStatusTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OPCacheStatus
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OPCacheStatus::getStatusData
     * @todo   Implement testGetStatusData().
     */
    public function testGetStatusData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheStatus::getCurrentStatus
     * @todo   Implement testGetCurrentStatus().
     */
    public function testGetCurrentStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheStatus::getMemoryInfo
     * @todo   Implement testGetMemoryInfo().
     */
    public function testGetMemoryInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheStatus::getMemoryUsage
     * @todo   Implement testGetMemoryUsage().
     */
    public function testGetMemoryUsage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheStatus::getStatistics
     * @todo   Implement testGetStatistics().
     */
    public function testGetStatistics()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheStatus::getScripts
     * @todo   Implement testGetScripts().
     */
    public function testGetScripts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
