<?php

namespace OPCache;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-03-12 at 16:17:57.
 */
class OPCacheConfigurationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OPCacheConfiguration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OPCacheConfiguration::getDirectives
     * @todo   Implement testGetDirectives().
     */
    public function testGetDirectives()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheConfiguration::getDirective
     * @todo   Implement testGetDirective().
     */
    public function testGetDirective()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheConfiguration::getDirectiveKeys
     * @todo   Implement testGetDirectiveKeys().
     */
    public function testGetDirectiveKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheConfiguration::getBlacklist
     * @todo   Implement testGetBlacklist().
     */
    public function testGetBlacklist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheConfiguration::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OPCacheConfiguration::checkDirectives
     * @todo   Implement testCheckDirectives().
     */
    public function testCheckDirectives()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
